### ISSUE TITLE
Copyright  indefinite 

### ISSUE THREAD

**Issue by Nilsonfsilva** [adriantombu/indefinite#1]
Hi!
the undefined is going to the Debian repositories.

However, I need to clarify about the copyright of the project.

Do they belong to Adrian Tombu?

**Comment by adriantombu** [comment]
Hey @Nilsonfsilva!

This project is a Rust port of a JavaScript library: I believe with the MIT license, I need to keep the original author of the Js lib in the license, but I see that I also forgot to add myself in the license file, let me fix that 😄

**Comment by adriantombu** [comment]
@Nilsonfsilva I'm closing this issue as the question has been answered. Feel free to reach out if you have any other questions!
